import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-landing-page',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './landing-page.component.html',
  styleUrls: ['./landing-page.component.scss']
})
export class LandingPageComponent {
  features = [
    {
      title: 'Practice Exams',
      description: 'Access a wide range of certification practice exams across different technologies and difficulty levels.',
      icon: 'assets/icons/exam.svg'
    },
    {
      title: 'AI-Generated Questions',
      description: 'Get custom exams generated by AI to test your knowledge in specific areas.',
      icon: 'assets/icons/ai.svg'
    },
    {
      title: 'Performance Tracking',
      description: 'Track your progress and identify areas for improvement with detailed performance analytics.',
      icon: 'assets/icons/analytics.svg'
    }
  ];
  
  technologies = [
    { name: 'Angular', icon: 'assets/icons/angular-logo.svg' }
  ];
}